# Triangle numbers are generated by adding the natural numbers T(7)=1+2+...+7=28
# Find first triangle number with over 500 factors

nfactors <- 500

found <- 0
index <- 1L # Which triangle number
num <- 1L # value of number
while(found==0){
  if(factors(num)>nfactors){
    found <- 1
    print(num)
  }else{
    index <- index + 1L
    num <- num + index
  }
}

factors <- function(x){
#  div <- seq_len(ceiling(x/2))
  div <- seq_len(ceiling(sqrt(x)))
  n <- sum(x%%div==0L)*2
  if(floor(sqrt(x))==sqrt(x)){
    return(n-1)
  }else{
    return(n)
  }
}