# Suppose we were only given the first two terms of this sequence. Working on the
#   principle that "simple is best" we should assume a linear relationship and
#   predict the next term to be 15 (common difference 7). Even if we were presented
#   with the first three terms, by the same principle of simplicity, a quadratic
#   relationship should be assumed.

# We shall define OP(k, n) to be the nth term of the optimum polynomial generating
#   function for the first k terms of a sequence. It should be clear that OP(k, n)
#   will accurately generate the terms of the sequence for n ≤ k, and potentially
#   the first incorrect term (FIT) will be OP(k, k+1); in which case we shall call
#   it a bad OP (BOP).

# As a basis, if we were only given the first term of sequence, it would be most
#   sensible to assume constancy; that is, for n ≥ 2, OP(1, n) = u1.

# Hence we obtain the following OPs for the cubic sequence: 
#  OP(1, n) = 1               1, 1, 1, 1, ...
#  OP(2, n) = 7n−6          	1, 8, 15, ...
#  OP(3, n) = 6n^2−11n+6     	1, 8, 27, 58, ...
#  OP(4, n) = n^3   	        1, 8, 27, 64, 125, ...
#  Clearly no BOPs exist for k ≥ 4.

# By considering the sum of FITs generated by the BOPs (indicated in red above), we
#   obtain 1 + 15 + 58 = 74.

# Consider the following tenth degree polynomial generating function:
#   u_n = 1 − n + n^2 − n^3 + n^4 − n^5 + n^6 − n^7 + n^8 − n^9 + n^10
# Find the sum of FITs for the BOPs.


# NOTE: Code works, but throws warnings in regards to the predict function

fn <- function(n){ 1-n+n^2-n^3+n^4-n^5+n^6-n^7+n^8-n^9+n^10 }
gen_samples <- function(x){ sapply(1:x, fn) }

vals <- gen_samples(11)
n <- 1:11
data <- data.frame(n,vals)

fit <- 0
for(degree in 1:10){
  model <- lm(data$vals ~
                poly(data$n,degree,raw=TRUE),
              data,
              c(rep(TRUE,degree),rep(FALSE,11-degree)))
  predictions <- predict(model,3) # Not sure why 3 is the magic number here
  fit <- fit + predictions[degree+1]
}
print(fit)
