#Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
#  Triangle   	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
#  Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
#  Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

# You can efficiently generate a set of any of these numbers. What's difficult is checking
#   to see if they're within a vector
# So instead, reverse the equation so that you can check if solving for n gives an integer
#   This can be done only as needed and is a much faster operation.

triangle <- function(n){ return(n*(n+1)/2) }
tris <- triangle(286:100000)

for(t in tris){
  if(((sqrt(8*t+1)+1)/4) %% 1 == 0){
    if(((sqrt(24*t+1)+1)/6) %% 1 == 0){
      print(t)
      break
    }
  }
}