# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal
#   numbers are:
#   1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48,
#   is not pentagonal.

# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are
#   pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

# CODE PRODUCES CORRECT ANSWER. RELATIVELY SLOW, ABOUT 8.5 SECONDS

pentagonal <- function(n){
  p <- n*(3*n-1) / 2
  return(p)
}

maximum <- 10000 # Chose an arbitrary stopping point
pents <- pentagonal(1:maximum)
lowest <- pents[maximum]

for(i in 1:maximum){
  poss <- pents[(pents-pents[i])<lowest]
  subs <- poss[(poss-pents[i]) %in% poss]
  
  if(length(subs)>0){
    adds <- subs[(subs+pents[i]) %in% poss]
    
    if(length(adds)>0){
      lowest <- min(c(lowest,abs(pents[i]-adds)))
    }
  }
}
print(lowest)